name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker buildx create --use
        docker buildx build --file Dockerfile --tag your-docker-hub-username/k8s:latest .
        docker buildx stop --builder default
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s:latest
